name: Build AAB

on:
  workflow_call:
    secrets:
      KEYSTORE_JKS:
        required: true
      KEYSTORE_PASSWORD:
        required: true
      KEY_PASSWORD:
        required: true
      KEY_ALIAS:
        required: true

jobs:
  build_aab:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Renderer
        uses: actions/download-artifact@v4
        with:
          name: renderer
          path: ./assets/renderer/

      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 17
          distribution: oracle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3
          channel: stable

      - name: Decode keystore.jks
        run: echo "${{ secrets.KEYSTORE_JKS }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Pub Get Packages
        run: flutter pub get

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: aab
          path: ./build/app/outputs/bundle/release/
