name: Deploy to Firebase App Distribution

on: workflow_dispatch

jobs:
  build_renderer:
    uses: ./.github/workflows/build_renderer.yaml

  build_aab:
    needs: build_renderer
    uses: ./.github/workflows/build_aab.yaml
    secrets:
      KEYSTORE_JKS: ${{ secrets.KEYSTORE_JKS }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

  deploy_to_firebase:
    runs-on: macos-latest
    needs: build_aab
    environment: Firebase App Distribution
    steps:
      - name: Download AAB
        uses: actions/download-artifact@v4
        with:
          name: aab
          path: ./

      - name: Upload AAB to Firebase
        uses: emertozd/Firebase-Distribution-Github-Action@v2
        with:
          appId: ${{ secrets.ANDROID_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: ./app-release.aab
