name: Deploy to Google Play Store Closed Test Track

on: workflow_dispatch

jobs:
  build_renderer:
    uses: ./.github/workflows/build_renderer.yaml

  build_aab:
    uses: ./.github/workflows/build_aab.yaml

  deploy_to_play_store:
    runs-on: ubuntu-latest
    steps:
      - name: Download AAB
        uses: actions/download-artifact@v4
        with:
          name: aab
          path: ./

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: novelglide
          workload_identity_provider: projects/569892023598/locations/global/workloadIdentityPools/github/providers/github-provider

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: com.kai_wu.novelglide
          releaseFiles: ./app-release.aab
          track: qa