name: Deploy to Google Play Store Internal

on: workflow_dispatch

jobs:
  build_renderer:
    uses: ./.github/workflows/build_renderer.yaml

  build_aab:
    needs: build_renderer
    uses: ./.github/workflows/build_aab.yaml
    secrets:
      KEYSTORE_JKS: ${{ secrets.KEYSTORE_JKS }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

  deploy_to_play_store:
    runs-on: ubuntu-latest
    needs: build_aab
    permissions:
     contents: 'read'
     id-token: 'write'
    steps:
      - name: Download AAB
        uses: actions/download-artifact@v4
        with:
          name: aab
          path: ./

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/569892023598/locations/global/workloadIdentityPools/github/providers/github-action-provider
          service_account: play-store@novelglide.iam.gserviceaccount.com

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: com.kai_wu.novelglide
          releaseFiles: ./app-release.aab
          track: qa
